# Generated by Django 4.1 on 2022-08-07 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_rename_country_city_state'),
        ('companies', '0004_rename_timeslots_timeslot'),
        ('users', '0002_rename_company_worked_profile_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geolocations.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
