# Generated by Django 4.1 on 2022-08-06 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('commercial_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
