# Generated by Django 4.1 on 2022-08-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('companies', '0003_accesspoint_timeslots_timeslots_start_before_end'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlots',
            new_name='TimeSlot',
        ),
    ]
