# Generated by Django 4.1 on 2022-08-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_timeslots_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspoint',
            old_name='state',
            new_name='active',
        ),
    ]
