# Generated by Django 4.1 on 2022-08-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_state_accesspoint_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='start_before_end',
        ),
    ]
