# Generated by Django 4.1 on 2022-08-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
